version: "3.9"
services:
  mlflow:
    build: .
    restart: always
    ports:
      - 5000:5000
    profiles:
      - "server"
    # entrypoint: ["mlflow", "ui", "--host", "0.0.0.0", "--default-artifact-root", "s3://mlflow-artifacts/", "--backend-store-uri", "postgresql://postgres:postgres@database:5432/mlflowdb"]
    entrypoint: ["mlflow", "ui", "--host", "0.0.0.0", "--backend-store-uri", "postgresql://postgres:postgres@database:5432/mlflowdb"]
    depends_on: 
      - database
    volumes:
      - mlflow:/root/.mlflow  
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflowdb
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: 
      - "db"
volumes:
  mlflow:
  db:
networks:
  default:
    name: mlflow-network
